title: Mads Kolind # your name (or website title) here
logo: "/images/mig.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently doing a Msc in Data Science at SDU (University of Southern Denmark)
  <br><br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/madskolind/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
